#!/bin/bash

set -e

[[ -z "$BUILD_NUMBER" ]] && echo "BUILD_NUMBER must be set" && exit 1

version=$(grep -m1 'version =' pyproject.toml | sed -E 's/version = "([^"]+)"/\1/')
tag=${version}-${BUILD_NUMBER}

repo_url="https://$GH_TOKEN@github.com/MassDynamics/md_form.git"
git_tag="v${tag}"
echo "Git tag ${git_tag}"
git tag "${git_tag}"
git push $repo_url "${git_tag}"

echo "+++ Git tag: ${git_tag}"
